### ISSUE TITLE
getCurrentCondition JSONException: No value for deg 

### ISSUE THREAD

**Issue by Twibit** [survivingwithandroid/WeatherLib#32]
I get the following error while using getCurrentCondition with OpenWeatherMap : 
 ```
org.json.JSONException: No value for deg
 at org.json.JSONObject.get(JSONObject.java:389)
 at org.json.JSONObject.getDouble(JSONObject.java:444)
 at com.survivingwithandroid.weather.lib.provider.openweathermap.OpenweathermapProvider.getFloat(OpenweathermapProvider.java:514)
 at com.survivingwithandroid.weather.lib.provider.openweathermap.OpenweathermapProvider.getCurrentCondition(OpenweathermapProvider.java:135)
 at com.survivingwithandroid.weather.lib.client.okhttp.WeatherDefaultClient$4.onResponse(WeatherDefaultClient.java:380)
 at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:162)
 at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
 at java.lang.Thread.run(Thread.java:818)
```

**Comment by levj220** [comment]
I get the following error as well, starting recently.  This only shows up using the OpenWeatherMap Provider:
```
org.json.JSONException: No value for humidity
at org.json.JSONObject.get(JSONObject.java:389)
at org.json.JSONObject.getInt(JSONObject.java:478)
at com.survivingwithandroid.weather.lib.provider.openweathermap.OpenweathermapProvider.getInt(OpenweathermapProvider.java:518)
at com.survivingwithandroid.weather.lib.provider.openweathermap.OpenweathermapProvider.getCurrentCondition(OpenweathermapProvider.java:124)
at com.survivingwithandroid.weather.lib.client.okhttp.WeatherDefaultClient$4.onResponse(WeatherDefaultClient.java:380)
at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:162)
at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
```

**Comment by Twibit** [comment]
As suggested by @HugoGressen in #28, maybe you should use a JSON library like GSON or Jackson to parse the results.
Also, is there an openweathermap change log ?

**Comment by survivingwithandroid** [comment]
The problem i'm facing with OWM is i can't find a doc describing if a tag is mandatory or not.
Anyway i will make these tags optional.
Thx for you support!

**Comment by athkalia** [comment]
I can confirm that this is causing my application to crash as well

**Comment by athkalia** [comment]
Any plans on when going to release this fix with optional tags ?

**Comment by swapps** [comment]
hi, i'm having the same issue, any coming fix ?

**Comment by survivingwithandroid** [comment]
In the master branch there is already a fix but you have to recompile the source.
I'm planning to release a new version as beta in this week.
Thx for your support!

**Comment by swapps** [comment]
Please let use know when it’s ready.

 

 

De : Surviving with android (by Francesco Azzola) [mailto:notifications@github.com] 
Envoyé : mercredi 14 octobre 2015 15:23
À : survivingwithandroid/WeatherLib
Cc : swapps
Objet : Re: [WeatherLib] getCurrentCondition JSONException: No value for deg (#32)

 

In the master branch there is already a fix but you have to recompile the source.
I'm planning to release a new version as beta in this week.
Thx for your support!

**Comment by survivingwithandroid** [comment]
The problem should b solved in 1.5.9 just released

**Comment by swapps** [comment]
hi, it still doesn't work, the api key isn't added when searching for city:

10-19 14:39:18.170: D/SwA(26713): Client [com.survivingwithandroid.weather.lib.client.volley.WeatherClientDefault@b31c86a]
10-19 14:39:18.336: E/Volley(26713): [3891] BasicNetwork.performRequest: Unexpected response code 401 for http://api.openweathermap.org/data/2.5/find?mode=json&type=like&q=Co

as you can see the apikey is missing in the url request﻿
